### ISSUE TITLE
DM the user that the bot is unable to message in a server due to a weird permissions error

### ISSUE THREAD

**Issue by sahil-kale** [BediBot/BediBot-Rewrite#67]
If the bot is physically unable to send a message, all of the errors will be missed. In order to avoid this, a DM should be sent with this error.

**Comment by zaydtahir** [comment]
- Create SendMessagePerm Precondition with special context property (dm = true)
- Update CommandDenied Listener to check for this property and if so, rather than sending error message in chat, send it in DM

**Comment by zaydtahir** [comment]
It seems like due to a limitation of the API, we can't read messages when we don't have send messages permission, so this is not possible. 

It would be very rare for an admin to accidentally take away the permissions for BediBot to send a message, so it should be fine.
